export const inputs = [
  {
    id: 1,
    name: "username",
    type: "text",
    placeholder: "Enter Username",
    errorMessage:
      "Username must be between 3 - 16 characters and cannot include any special characters",
    label: "Username",
    pattern: "^[A-Za-z0-9]{3,16}$",
    autoComplete: "off",
    required: true,
  },
  {
    id: 2,
    name: "password",
    type: "password",
    placeholder: "EnterPassword",
    errorMessage:
      "Password must be between 8 - 20 characters and include at least 1 upper case letter, 1 number, and 1 special character",
    label: "Password",
    pattern:
      "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$",
    autoComplete: "off",
    required: true,
  },
  {
    id: 3,
    name: "f_name",
    type: "text",
    placeholder: "Enter First Name",
    label: "First Name",
    pattern: "^[a-zA-Z0-9 ]*$",
    autoComplete: "off",
    required: true,
  },
  {
    id: 4,
    name: "l_name",
    type: "text",
    placeholder: "Enter Last Name",
    label: "Last Name",
    pattern: "^[a-zA-Z0-9 ]*$",
    autoComplete: "off",
    required: true,
  },
  {
    id: 5,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "Email must be valid",
    label: "Email",
    autoComplete: "off",
    required: true,
  },
];
